name: Build and Publish Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch, optional)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/elbelgg/pterodactylwings:latest
            ghcr.io/elbelgg/pterodactylwings:${{ github.sha }}
          build-args: |
            WINGS_VERSION=latest
            WINGS_ARCH=linux_amd64
          platforms: linux/amd64
          # cache-from and cache-to help speed up repeated builds (optional)
          cache-from: type=gha
          cache-to: type=gha,mode=max
